In [4]:
import pandas as pd
import os

In [5]:
df_OBIS_dataset_classification = pd.read_csv('Dataset_and_Org_classifications/OBIS_dataset_metrics.csv')
df_OBIS_dataset_classification.set_index('dataset_id', inplace=True)

In [6]:
df_OBIS_dataset_classification

,Data providers,Total Occurrences,PrivateFlag,PercProvPRIVATE,PercProvPUBLIC,PercProvUNKNOWNPUBLIC,PercProvOUTLIER,WeightedPercOccurrencesPrivate
dataset_id,,,,,,,,
d6ae6af8-8eac-4fbd-9ce5-b49b1137351c,['University of Queensland'],3665,False,0.0,100.000000,0.000000,0.0,0.0
96041282-9386-4a8a-a564-fd753f1222b0,['CSIRO National Collections and Marine Infras...,19763,False,0.0,100.000000,0.000000,0.0,0.0
61dc18bb-e2ec-43a1-949c-120d58235b61,"['The Australian National University', 'CSIRO ...",1960,False,0.0,100.000000,0.000000,0.0,0.0
0c7b3f51-33c8-494c-ab8a-c5bd28f40f87,['Delaware Museum of Nature and Science – Moll...,34280,False,0.0,0.000000,100.000000,0.0,0.0
8ea620e9-37d5-4ff6-9a02-0bc94356c2d5,"['Invert-E-Base Portal', 'Malacology Collectio...",164632,False,0.0,0.000000,100.000000,0.0,0.0
...,...,...,...,...,...,...,...,...
7aee17f1-d6e8-4204-a4b2-eafdf89563cf,['Intergovernmental Oceanographic Commission o...,229575,False,0.0,66.666667,33.333333,0.0,0.0
ce92b079-6389-4880-99d8-1a97fb171211,['Intergovernmental Oceanographic Commission o...,835,False,0.0,100.000000,0.000000,0.0,0.0
4a4bc032-e738-4102-b67f-445578b656d9,['Intergovernmental Oceanographic Commission o...,1709,False,0.0,100.000000,0.000000,0.0,0.0
63108715-3d0c-4a26-847f-16ca305c9cb1,['Intergovernmental Oceanographic Commission o...,908,False,0.0,100.000000,0.000000,0.0,0.0
75e2a2b6-f58f-4c43-aefd-878cee7865b1,"['Australian Antarctic Division', 'Intergovern...",556,False,0.0,100.000000,0.000000,0.0,0.0

In [8]:
# Function to process chunks
def process_chunk(chunk, df_OBIS_dataset_classification):
    # Merge the chunk with df_OBIS_dataset_classification to add PrivateFlag
    chunk = chunk.merge(df_OBIS_dataset_classification[['PrivateFlag']], left_on='dataset_id', right_index=True, how='left')
    return chunk

In [9]:
input_OBIS_occurence_file = 'input_occurence_data/obis_filtered.csv'

# Initialize progress tracking
chunk_size = 10**6  # Adjust chunk size as needed
total_rows = 128621187  # Hardcoded total number of rows
total_chunks = (total_rows // chunk_size) + 1

In [10]:
output_path = 'output_occurence_data_classified/obis_classified.csv'
private_output_path = 'output_occurence_data_classified/obis_classified_privateonly.csv'

In [11]:
# # Check loading of the file (and if necessary QC length)
# dfOBIS = pd.read_csv(input_OBIS_occurence_file, nrows=10000)
# dfOBIS

In [12]:
# Check if output files already exist
if os.path.exists(output_path) or os.path.exists(private_output_path):
    print("One or both of the output files already exist.")
    print("Please delete or rename the following files before proceeding:")
    if os.path.exists(output_path):
        print(f"- {output_path}")
    if os.path.exists(private_output_path):
        print(f"- {private_output_path}")
    print("Aborting the process.")
    
else:
    # Write headers to output files
    header_written = False
    private_header_written = False

    # Open files for writing
    with open(output_path, 'w') as all_file, open(private_output_path, 'w') as private_file:
        # Process dfOBIS in chunks
        for i, chunk in enumerate(pd.read_csv(input_OBIS_occurence_file, chunksize=chunk_size)):
            # Process the chunk
            processed_chunk = process_chunk(chunk, df_OBIS_dataset_classification)
            
            # Write processed chunk to the main CSV file
            processed_chunk.to_csv(all_file, mode='a', header=not header_written, index=False)
            
            # Write rows where PrivateFlag is True to the private CSV file
            private_rows = processed_chunk[processed_chunk['PrivateFlag'] == True]
            private_rows.to_csv(private_file, mode='a', header=not private_header_written, index=False)
            
            # Update progress
            print(f'\rProcessing: Chunk {i + 1}/{total_chunks}', end='')
            
            # Update header flags
            header_written = True
            private_header_written = True

    # Print final message
    print(f'\nProcessing complete. Outputs written to {output_path} and {private_output_path}')

Processing: Chunk 129/129
Processing complete. Outputs written to output_occurence_data_classified/filtered_obis_parquet_classified.csv and output_occurence_data_classified/filtered_obis_parquet_classified_privateonly.csv

### Quality control etc

In [13]:
dfOBISclass = pd.read_csv(output_path, nrows=1000)
dfOBISclass

,dataset_id,decimalLongitude,decimalLatitude,date_year,PrivateFlag
0,0c1cb7e9-c7d1-4643-b245-daa8839a183f,-3.135050,58.911830,2009.0,False
1,0c1cb7e9-c7d1-4643-b245-daa8839a183f,-6.887870,58.217500,2010.0,False
2,0c1cb7e9-c7d1-4643-b245-daa8839a183f,1.281997,58.690365,2006.0,False
3,0c1cb7e9-c7d1-4643-b245-daa8839a183f,-1.104040,60.327460,2008.0,False
4,0c1cb7e9-c7d1-4643-b245-daa8839a183f,1.744569,61.393000,2006.0,False
...,...,...,...,...,...
995,2891a788-9f30-4413-8f73-9e7686890e9d,-124.162340,41.140312,NaN,False
996,9a2ca2e2-e8fb-4de6-9c7c-a532578494ca,0.500000,54.750000,2000.0,False
997,2891a788-9f30-4413-8f73-9e7686890e9d,-82.469536,23.322355,NaN,False
998,9a2ca2e2-e8fb-4de6-9c7c-a532578494ca,0.500000,54.750000,2000.0,False
999,2891a788-9f30-4413-8f73-9e7686890e9d,-88.186670,17.200000,NaN,False

In [ ]:
dfOBISclass = pd.read_csv(output_path)

In [6]:
dfOBISclass

,dataset_id,decimalLongitude,decimalLatitude,date_year,PrivateFlag
0,0c1cb7e9-c7d1-4643-b245-daa8839a183f,-3.135050,58.911830,2009.0,False
1,0c1cb7e9-c7d1-4643-b245-daa8839a183f,-6.887870,58.217500,2010.0,False
2,0c1cb7e9-c7d1-4643-b245-daa8839a183f,1.281997,58.690365,2006.0,False
3,0c1cb7e9-c7d1-4643-b245-daa8839a183f,-1.104040,60.327460,2008.0,False
4,0c1cb7e9-c7d1-4643-b245-daa8839a183f,1.744569,61.393000,2006.0,False
...,...,...,...,...,...
128621182,38535a43-2982-4479-88c1-8303f7ee8665,-72.773800,38.820200,1983.0,False
128621183,38535a43-2982-4479-88c1-8303f7ee8665,-72.773800,38.820200,1983.0,False
128621184,38535a43-2982-4479-88c1-8303f7ee8665,-72.773800,38.820200,1983.0,False
128621185,38535a43-2982-4479-88c1-8303f7ee8665,-72.773800,38.820200,1983.0,False
128621186,38535a43-2982-4479-88c1-8303f7ee8665,-72.773800,38.820200,1983.0,False

In [7]:
len(dfOBISclass)

128621187

NB - expected full length of OBIS (as of August 2024) is 128621187

In [8]:
# Count number of rows with PrivateFlag True
private_flag_count = dfOBISclass[dfOBISclass['PrivateFlag'] == True].shape[0]

# Count number of rows with specific dataset_ids for QC:
dataset_id_counts = {
    'e2c4a839-89b5-484f-a63c-df89c2f9f974': dfOBISclass[dfOBISclass['dataset_id'] == 'e2c4a839-89b5-484f-a63c-df89c2f9f974'].shape[0],
    '48cb8624-a221-47ed-9a6d-b99b0bb394e0': dfOBISclass[dfOBISclass['dataset_id'] == '48cb8624-a221-47ed-9a6d-b99b0bb394e0'].shape[0],
    '5055f146-1a0a-41be-a747-24968c2cf584': dfOBISclass[dfOBISclass['dataset_id'] == '5055f146-1a0a-41be-a747-24968c2cf584'].shape[0]
}

# Print the results
print(f"Number of rows with PrivateFlag True: {private_flag_count}")
for dataset_id, count in dataset_id_counts.items():
    print(f"Number of rows with dataset_id {dataset_id}: {count}")

Number of rows with PrivateFlag True: 6440698
Number of rows with dataset_id e2c4a839-89b5-484f-a63c-df89c2f9f974: 2176406
Number of rows with dataset_id 48cb8624-a221-47ed-9a6d-b99b0bb394e0: 2331595
Number of rows with dataset_id 5055f146-1a0a-41be-a747-24968c2cf584: 132078

In [9]:
# Get unique values and their counts in the PrivateFlag column, including NaNs
private_flag_unique_values = dfOBISclass['PrivateFlag'].value_counts(dropna=False)

# Print the unique values and their counts
print("Unique values in the PrivateFlag column and their counts:")
print(private_flag_unique_values)

Unique values in the PrivateFlag column and their counts:
PrivateFlag
False    122108944
True       6440698
NaN          71545
Name: count, dtype: int64

In [10]:
# Get unique dataset_ids where the PrivateFlag column is NaN
unique_dataset_ids_with_nan = dfOBISclass[pd.isna(dfOBISclass['PrivateFlag'])]['dataset_id'].unique()

# Print the unique dataset_ids
print("Unique dataset_ids where the PrivateFlag column is NaN:")
print(unique_dataset_ids_with_nan)

Unique dataset_ids where the PrivateFlag column is NaN:
['8196bdec-73b7-4b8d-84c3-ad503d878026'
 '3f2c1827-a206-41c4-bc53-58267dd28cbd'
 'f4775120-afcc-4350-9e03-649c978f6070'
 'cc52b36b-0095-4af9-a3ca-a9beb3d829a2'
 'c9b40d2d-e9c7-4d2d-af55-005fff4e4c7b'
 '287f44a3-d5b7-4efb-8708-809d1a5323ae'
 '8b5b2a47-e4ed-4da9-8230-da0783a5e47b'
 '95676710-8ea4-4311-96dc-065d02bd180e'
 '1410110e-64ca-4ce7-896a-3adc4a779f5d'
 '2a1526e5-174b-4691-8410-3015f40b1309'
 '0deadda5-75b2-47e3-918d-5d1c12f0583c'
 '6c6df99a-7670-40b4-8eaa-f2e374ed4da6'
 '9080ddf4-075c-4bf1-875c-338998c7f897'
 '4fc658bf-d9b6-408b-ac2b-2e5e90bcba4a'
 'fbe8a17d-9734-471c-98f5-98c837c49bf4'
 '277f9300-b846-47f3-bea2-d2c082a5f8fb'
 'd0e165db-f2e6-4685-98e7-c9bf0b5bb7c4'
 'c33c5816-4bc2-4d44-8719-201920724ac2'
 '1cbe83fd-9097-484b-8784-97265d98fef8'
 'fea6f193-510a-493b-8b53-7661cffcde10'
 '9362fac0-8252-4afe-9855-822113401709'
 'ac8e049c-3ef0-4cfb-af62-aa757f1abd20'
 'ee38cf35-ccff-4e2e-bd57-ea5a350bfa6a'
 '6dc643dc-1a98-4292-b1f6-483ed5659146'
 '438e1520-b5e4-4a58-8649-29dbe3abb146'
 '91bfe0bd-efdb-47cc-a646-c080b5c64785'
 '211c1939-18bd-4ed4-b6fb-9c73394eb4bd'
 '398dba6f-a5ea-48f5-8e64-9e4c30aba061'
 'a45a75ba-3f56-471b-8900-3f25afd73962'
 'a9ad33c5-2bf4-4c62-8ea7-cc832f449c77'
 '11d24443-3d62-4104-b111-027b1bdb1b3a'
 'dc3330bf-fa60-4aed-acef-5de564a9c6f6'
 '35be881a-7079-4a1a-92fa-9517eaa23266'
 '3ef652f0-bbf3-4a20-965e-bf232baa9247'
 'c04a830a-51ee-44d7-959a-98b5044eba7e'
 '21de83f5-a0d9-4eaf-9d86-5d60af807643'
 '5f9b82b4-f164-4578-8ac9-93acb1b3384e'
 'f4ed6def-a0d1-414d-9ada-17c86236ecf2'
 '02f40540-6b5e-4d3e-8fde-1cfcf220fb04'
 '549b91f2-2e88-4e7a-8842-ac48b85f50af'
 'f49b2ebe-d278-4454-8b3e-c04eb3c0362d'
 '7e923d66-d63c-4b3d-8ece-f5a7e4a97d70'
 '324e6a43-a41f-481d-8d21-3cf510a5b239'
 '3e8d2247-b00d-4fd2-98cb-c17fcb72f15c'
 'd51bbff1-c3ad-400a-a066-1e0461774ad5']

In [5]:
dfOBISclassprivate = pd.read_csv('filtered_obis_parquet_classified_privateonly.csv')

In [6]:
len(dfOBISclassprivate)

6440698

In [7]:
# Count number of rows with PrivateFlag True
private_flag_count = dfOBISclassprivate[dfOBISclassprivate['PrivateFlag'] == True].shape[0]

# Count number of rows with specific dataset_ids
dataset_id_counts = {
    'e2c4a839-89b5-484f-a63c-df89c2f9f974': dfOBISclassprivate[dfOBISclassprivate['dataset_id'] == 'e2c4a839-89b5-484f-a63c-df89c2f9f974'].shape[0],
    '48cb8624-a221-47ed-9a6d-b99b0bb394e0': dfOBISclassprivate[dfOBISclassprivate['dataset_id'] == '48cb8624-a221-47ed-9a6d-b99b0bb394e0'].shape[0],
    '5055f146-1a0a-41be-a747-24968c2cf584': dfOBISclassprivate[dfOBISclassprivate['dataset_id'] == '5055f146-1a0a-41be-a747-24968c2cf584'].shape[0]
}

# Print the results
print(f"Number of rows with PrivateFlag True: {private_flag_count}")
for dataset_id, count in dataset_id_counts.items():
    print(f"Number of rows with dataset_id {dataset_id}: {count}")

Number of rows with PrivateFlag True: 6440698
Number of rows with dataset_id e2c4a839-89b5-484f-a63c-df89c2f9f974: 2176406
Number of rows with dataset_id 48cb8624-a221-47ed-9a6d-b99b0bb394e0: 2331595
Number of rows with dataset_id 5055f146-1a0a-41be-a747-24968c2cf584: 132078